Hide the comment section after cancelling a top level comment
Dear-Blueno/dearblueno pull request #19
Opened 2022-04-23 12:04 UTC by j-f1

Previously, clicking “comment” and then “cancel” on a post with no comments would leave the divider line visible.

2022-04-25 20:39 UTC, DearBlueno requested changes

2022-04-25 20:39 UTC, DearBlueno commented on client/src/components/feeds/post/comments/CommentSection.tsx
> -  useEffect(() => {
As a result of this change, the optimistic update when submitting a top level comment no longer appears to work.

Demo: https://streamable.com/w5wmn0

2022-04-26 12:16 UTC, j-f1 commented
Fixed!

2022-05-16 09:32 UTC, DearBlueno approved these changes

2022-05-17 06:21 UTC, merged